---
- hosts: all, localhost
  gather_facts: no
  pre_tasks:
    - set_fact: trex_user_password={{ trex_user_password }}
      no_log: true

  # ASSUMPTION: SSH-key access is already setup for this initial root-privileged user
  # (or user passes in "--ask-become-..." or in hosts.yaml file) - see README.md
  become: yes
  roles:
  - role: base_linux_platform_deps
  - role: trex_generator_software



